language: java
after_success: tools/travis-deploy.sh

jdk:
  - openjdk7

env:
  global:
    - secure: "f85rpIcNM57zkeQZpughzSwHqyQYtvh63RJyp/95e8Vkwxt4zYPiFZGWGTCxof/nKRgMgHZZZHmV/QcskivbhGWHCkzlf1re4uz5khI0qPSSyDHTsa6QjqFkKyxXeQA7TqPnNaZGHriqUQKdi1AcAxuUzkN8dG0JbyHxn5XBmoM="
    - secure: "iDE+kwYw7WWuBoXaqZI+i0JmxuwWxyonq6407VmkXdJre0OhmHyAuCJAyYqIUtuyps9WoE49EY7v+CxELtQ19Tnc1PLumqdklSnXKvbOYSBeSysybXinWVEbMwGDwpx3dL4BxB8QqJJC9J+H/mGHS8lfOadxkIIHEh1id2n+iWM="
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
